# Generated by Django 2.2.8 on 2020-10-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='image2',
            field=models.ImageField(default='default.jpg', upload_to='works/'),
        ),
    ]
